# Project configuration for WikiArt image classification

# Global Paths
paths:
  train_dir: "../data/train"
  val_dir: "../data/val"
  test_dir: "../data/test"
  models_dir: "../models"
  results_dir: "../models_results"

# Global Data/Training
num_classes: 23
max_epochs: 100
seed: 42

# Model-specific configs
models:
  baseline:
    checkpoint: "../models/baseline/baseline_best.keras"
    history: "../models/baseline/baseline_history.json"
    batch_size: 32
  resnet50:
    checkpoint: "../models/resnet50/resnet50_best.keras"
    history: "../models/resnet50/resnet50_history.json"
    batch_size: 32
  residual_block:
    checkpoint: "../models/residual_block/residual_block_best.keras"
    history: "../models/residual_block/residual_block_history.json"
    batch_size: 32
  efficientnetb3:
      checkpoint: ../models/efficientnetb3/efficientnetb3_best.keras
      history: ../models/efficientnetb3/efficientnetb3_history.pkl
  efficientnetb5:
      checkpoint: ../models/efficientnetb5/efficientnetb5_best.keras
      history: ../models/efficientnetb5/efficientnetb5_history.json
  vgg16:
    checkpoint: ../models/vgg16/vgg16_best.keras
    history: ../models/vgg16_history.json
    batch_size: 32
  convnexttiny:
    checkpoint: ../models/convnexttiny_best.keras
    history: ../models/convnexttiny_history.json
    batch_size: 32